CREATE TABLE admins (id TEXT PRIMARY KEY, email TEXT COLLATE NOCASE NOT NULL UNIQUE, name TEXT NOT NULL, password_hash TEXT NOT NULL, mfa_secret TEXT NOT NULL, mfa_step INTEGER NOT NULL DEFAULT -1, role TEXT NOT NULL CHECK(role IN ('owner','administrator','moderator','observer')), created_at INTEGER NOT NULL, last_login_at INTEGER NOT NULL DEFAULT 0, disabled_at INTEGER NOT NULL DEFAULT 0, failed_attempts INTEGER NOT NULL DEFAULT 0, locked_until INTEGER NOT NULL DEFAULT 0);
CREATE TABLE admin_sessions (id TEXT PRIMARY KEY, token_hash TEXT UNIQUE NOT NULL, admin_id TEXT NOT NULL REFERENCES admins(id), created_at INTEGER NOT NULL, last_seen_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, revoked_at INTEGER NOT NULL DEFAULT 0);
CREATE INDEX idx_admin_session_owner ON admin_sessions(admin_id);
CREATE TABLE admin_invites (id TEXT PRIMARY KEY, token_hash TEXT UNIQUE NOT NULL, role TEXT NOT NULL, email TEXT NOT NULL DEFAULT '', created_by TEXT NOT NULL, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, used_at INTEGER NOT NULL DEFAULT 0, revoked_at INTEGER NOT NULL DEFAULT 0);
CREATE TABLE admin_enrollments (token_hash TEXT PRIMARY KEY, invite_id TEXT NOT NULL REFERENCES admin_invites(id), email TEXT NOT NULL, name TEXT NOT NULL, password_hash TEXT NOT NULL, mfa_secret TEXT NOT NULL, expires_at INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE admin_recovery (admin_id TEXT NOT NULL REFERENCES admins(id), code_hash TEXT UNIQUE NOT NULL, used_at INTEGER NOT NULL DEFAULT 0);
CREATE TABLE admin_limits (bucket TEXT PRIMARY KEY, hits INTEGER NOT NULL, reset_at INTEGER NOT NULL);
CREATE TABLE audit_events (id INTEGER PRIMARY KEY AUTOINCREMENT, at INTEGER NOT NULL, actor_id TEXT NOT NULL, actor_name TEXT NOT NULL, session_id TEXT NOT NULL, action TEXT NOT NULL, object_id TEXT NOT NULL, result TEXT NOT NULL, source TEXT NOT NULL, details TEXT NOT NULL);
CREATE INDEX idx_audit_at ON audit_events(at);
CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit_events BEGIN SELECT RAISE(ABORT,'Audit events are append-only'); END;
CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit_events BEGIN SELECT RAISE(ABORT,'Audit events are append-only'); END;
