import test from 'node:test';
import {sessionCookie} from '../lib/local-session.mjs';
import {createAdminServer} from '../admin/server.mjs';
import {beginEnrollment,finishEnrollment,totp} from '../admin/security.mjs';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {setTimeout as delay} from 'node:timers/promises';

const root=fileURLToPath(new URL('../',import.meta.url));
test('starts without a worker runtime and persists signed-in module data',{timeout:180000},async()=>{
  const data=await mkdtemp(path.join(tmpdir(),'memespace-startup-'));
  const port=Number(process.env.MEMESPACE_TEST_PORT||5381),base=`http://127.0.0.1:${port}`;
  const hook=new URL('./no-worker-runtime.mjs',import.meta.url).href;
  let log='',exit=null,adminApp=null;const priorData=process.env.MEMESPACE_DATA_DIR;process.env.MEMESPACE_DATA_DIR=data;
  const child=spawn(process.execPath,['scripts/local.mjs',process.env.MEMESPACE_TEST_MODE==='serve'?'serve':'start'],{cwd:root,stdio:['ignore','pipe','pipe'],env:{...process.env,MEMESPACE_PORT:String(port),MEMESPACE_DATA_DIR:data,NODE_OPTIONS:`${process.env.NODE_OPTIONS||''} --import=${hook}`}});
  child.stdout.on('data',c=>log+=c);child.stderr.on('data',c=>log+=c);child.once('exit',code=>exit=code??1);
  async function call(route,body,cookie,extra={}){
    return fetch(base+route,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'Content-Type':'application/json',Origin:base}),...(cookie?{Cookie:cookie}:{}),...extra},body:body===undefined?undefined:JSON.stringify(body),redirect:'manual'});
  }
  try{
    let ready=false;
    for(let i=0;i<240;i++){
      if(exit!==null)assert.fail('Local server exited before readiness:\n'+log);
      try{const r=await call('/api/health');if(r.status===200&&(await r.json()).ok){ready=true;break}}catch{}
      await delay(250);
    }
    assert.ok(ready,'Local server did not become ready:\n'+log);
    const page=await call('/');assert.equal(page.status,200);assert.match(await page.text(),/Everything begins/);
    for(const asset of ['head.bin','brain.bin']){const r=await call('/geometry/'+asset);assert.equal(r.status,200);assert.ok((await r.arrayBuffer()).byteLength>100000)}
    assert.equal((await call('/api/profile')).status,401);
    assert.equal((await call('/api/profile',undefined,undefined,{'oai-authenticated-user-id':'spoof','oai-authenticated-user-email':'spoof@example.com'})).status,401);
    assert.deepEqual(await (await call('/api/auth/session')).json(),{account:null,sessionCount:0});
    assert.equal((await call('/api/auth/register',{identifier:'TEST@LOCALHOST',displayName:'Test account',password:'valid-local-password'},undefined,{Origin:'https://untrusted.example'})).status,403);
    const registration=await call('/api/auth/register',{identifier:'TEST@LOCALHOST',displayName:'Test account',password:'valid-local-password'});assert.equal(registration.status,201);
    const registered=await registration.json();assert.equal(registered.account.email,'test@localhost');assert.equal(registered.account.needsPasswordSetup,false);
    const registeredCookie=registration.headers.get('set-cookie')?.split(';')[0];assert.match(registeredCookie||'',/^memespace_session=/);
    assert.equal((await call('/api/auth/register',{identifier:' test@localhost ',displayName:'Other',password:'another-valid-password'})).status,409);
    assert.equal((await call('/api/auth/session',undefined,registeredCookie)).status,200);
    assert.equal((await call('/api/auth/login',{identifier:'test@localhost',password:'wrong-password'})).status,401);
    const reLogin=await call('/api/auth/login',{identifier:'test@localhost',password:'valid-local-password'});assert.equal(reLogin.status,200);
    const testCookie=reLogin.headers.get('set-cookie')?.split(';')[0];assert.match(testCookie||'',/^memespace_session=/);
    assert.equal((await call('/api/auth/sessions',undefined,testCookie)).status,200);
    assert.equal((await call('/api/auth/sessions/revoke-all',{},testCookie)).status,200);
    assert.equal((await call('/api/profile',{name:'Test profile',bio:'Persisted through identity reload.'},testCookie)).status,200);
    assert.equal((await call('/api/saved',{kind:'bookmark',key:'auth-story',payload:{title:'Auth story'}},testCookie)).status,200);
    assert.equal((await call('/api/chat',{text:'Identity persistence works',channel:'general'},testCookie)).status,201);
    const exportResponse=await call('/api/auth/export',undefined,testCookie);assert.equal(exportResponse.status,200);const exportText=await exportResponse.text();assert.equal(exportText.includes('passwordHash'),false);assert.equal(exportText.includes('tokenHash'),false);
    assert.equal((await call('/api/auth/password',{currentPassword:'valid-local-password',newPassword:'updated-local-password'},testCookie)).status,200);
    assert.equal((await call('/api/auth/logout',{},testCookie)).status,200);
    const relogin=await call('/api/auth/login',{identifier:'test@localhost',password:'updated-local-password'});assert.equal(relogin.status,200);const reloginCookie=relogin.headers.get('set-cookie')?.split(';')[0];
    assert.equal((await (await call('/api/profile',undefined,reloginCookie)).json()).profile.name,'Test profile');
    assert.ok((await (await call('/api/saved',undefined,reloginCookie)).json()).items.some(i=>i.item_key==='auth-story'));
    assert.ok((await (await call('/api/chat?channel=general',undefined,reloginCookie)).json()).messages.some(m=>m.text==='Identity persistence works'));
    const deletionLogin=await call('/api/auth/login',{identifier:'test@localhost',password:'updated-local-password'});const deletionCookie=deletionLogin.headers.get('set-cookie')?.split(';')[0];
    const authDeletion=await fetch(base+'/api/auth/account',{method:'DELETE',headers:{'Content-Type':'application/json',Origin:base,Cookie:deletionCookie},body:JSON.stringify({confirmation:'DELETE MY ACCOUNT',currentPassword:'updated-local-password'})});
    assert.equal(authDeletion.status,200);
    assert.deepEqual(await (await call('/api/auth/session',undefined,deletionCookie)).json(),{account:null,sessionCount:0});
    const anonymousShortcut=await call('/signin-with-chatgpt');assert.equal(anonymousShortcut.headers.get('location'),'/?signin=1');
    const oldCookie=sessionCookie().split(';')[0];
    const login=await call('/signin-with-chatgpt?return_to=%2F%23profile',undefined,oldCookie);assert.equal(login.status,303);
    const cookie=login.headers.get('set-cookie')?.split(';')[0];assert.ok(cookie);
    const legacyState=await (await call('/api/auth/session',undefined,cookie)).json();assert.equal(legacyState.account.needsPasswordSetup,true);
    assert.equal((await call('/api/auth/password',{newPassword:'legacy-owner-password',setup:true},cookie)).status,200);
    assert.equal((await call('/api/profile',{name:'Local test',bio:'Persists on this computer.'},cookie)).status,200);
    assert.equal((await (await call('/api/profile',undefined,cookie)).json()).profile.name,'Local test');
    assert.equal((await call('/api/profile',{name:'Untrusted',bio:''},cookie,{Origin:'https://untrusted.example'})).status,403);
    assert.equal((await call('/api/saved',{kind:'bookmark',key:'doge',payload:{title:'Doge'}},cookie)).status,200);
    assert.equal((await (await call('/api/saved',undefined,cookie)).json()).items[0].item_key,'doge');
    const note={kind:'note',key:'wallets',payload:{title:'Wallets',text:'My own learning notes.'}};
    assert.equal((await call('/api/saved',note,cookie)).status,200);
    assert.equal((await call('/api/saved',{...note,payload:{...note.payload,text:'Updated notes.'}},cookie)).status,200);
    const notes=(await (await call('/api/saved',undefined,cookie)).json()).items.filter(i=>i.kind==='note');
    assert.equal(notes.length,1);assert.equal(notes[0].payload.text,'Updated notes.');
    assert.equal((await call('/api/saved',{...note,payload:{title:'Wallets',text:'x'.repeat(1201)}},cookie)).status,400);
    const creation={kind:'meme',key:'studio-test',payload:{top:'TOP',bottom:'BOTTOM',image:'brain',fontSize:54,color:'#b4ffc8'}};
    assert.equal((await call('/api/saved',creation,cookie)).status,200);
    assert.equal((await call('/api/saved',{...creation,payload:{...creation.payload,fontSize:500}},cookie)).status,400);
    assert.equal((await call('/api/saved',{...creation,payload:{...creation.payload,color:'invalid'}},cookie)).status,400);
    const deletion=await fetch(base+'/api/saved',{method:'DELETE',headers:{'Content-Type':'application/json',Origin:base,Cookie:cookie},body:JSON.stringify({kind:'note',key:'wallets'})});
    assert.equal(deletion.status,200);
    assert.ok(!(await (await call('/api/saved',undefined,cookie)).json()).items.some(i=>i.kind==='note'));
    assert.equal((await call('/api/chat',{text:'Local runtime works',channel:'general'},cookie)).status,201);
    const chat=await (await call('/api/chat?channel=general',undefined,cookie)).json();assert.equal(chat.messages[0].text,'Local runtime works');assert.equal(chat.messages[0].mine,true);
    assert.equal((await call('/api/chat/like',{id:chat.messages[0].id,enabled:true},cookie)).status,200);
    assert.equal((await (await call('/api/chat?channel=general',undefined,cookie)).json()).messages[0].likes,1);
    assert.equal((await call('/api/profile',undefined,cookie+'tampered')).status,401);
    assert.equal((await call('/api/profile',undefined,oldCookie)).status,401,'old owner cookie cannot bypass the claimed password');
    assert.equal((await call('/signin-with-chatgpt')).headers.get('location'),'/?signin=1');
    assert.equal((await call('/admin')).status,404,'admin UI is absent from the public website');
    assert.equal((await call('/api/admin/users')).status,404,'admin API is absent from the public website');
    const adminPort=5394,adminBase=`http://127.0.0.1:${adminPort}`;
    adminApp=await createAdminServer({root,port:adminPort,sitePort:port});await new Promise(resolve=>adminApp.server.listen(adminPort,'127.0.0.1',resolve));
    const invite=adminApp.bootstrap(),enrollment=beginEnrollment(adminApp.security,adminApp.key,{invitation:invite.token,identifier:'integration@example.test',displayName:'Integration operator',password:'integration-admin-password'});
    const enrolled=finishEnrollment(adminApp.security,adminApp.key,{enrollmentToken:enrollment.enrollmentToken,code:totp(enrollment.secret)}),adminCookie='memespace_control='+enrolled.token;
    const session=await (await fetch(adminBase+'/api/session',{headers:{Cookie:adminCookie}})).json();
    const adminCall=(route,input)=>fetch(adminBase+'/api/'+route,{method:'POST',headers:{Cookie:adminCookie,Origin:adminBase,'Content-Type':'application/json','X-CSRF-Token':session.csrf},body:JSON.stringify(input)});
    const publicCatalog=await (await call('/api/arcade')).json();assert.equal(publicCatalog.games.length,6);assert.ok(publicCatalog.games.every(g=>g.enabled));
    const adminGames=await (await fetch(adminBase+'/api/games',{headers:{Cookie:adminCookie}})).json();assert.equal(adminGames.items.length,6);
    assert.equal((await adminCall('games/pool',{action:'pause',reason:'Table maintenance window'})).status,200);
    assert.equal((await (await call('/api/arcade')).json()).games.find(g=>g.id==='pool').enabled,false);
    assert.equal((await adminCall('games/pool',{action:'enable',reason:'Table maintenance complete'})).status,200);
    assert.equal((await (await call('/api/arcade')).json()).games.find(g=>g.id==='pool').enabled,true);
    assert.equal((await call('/api/arcade',{action:'pause'})).status,405,'the public catalog is read-only');
    assert.equal((await call('/api/profile',undefined,adminCookie)).status,401);
    assert.equal((await fetch(adminBase+'/api/users',{headers:{Cookie:cookie}})).status,401);
    assert.equal((await call('/api/reports',{messageId:chat.messages[0].id},cookie)).status,200);
    const reports=await (await fetch(adminBase+'/api/reports',{headers:{Cookie:adminCookie}})).json();
    assert.equal((await adminCall('reports/'+reports.items[0].id,{action:'hide',reason:'Integration moderation review'})).status,200);
    assert.equal((await (await call('/api/chat')).json()).messages.length,0);
    assert.equal((await adminCall('messages/'+chat.messages[0].id,{action:'restore',reason:'Integration appeal approved'})).status,200);
    assert.equal((await (await call('/api/chat')).json()).messages.length,1);
    const announcement={title:'Community update',body:'Published from the separate Control Center.',tone:'info',status:'draft'};
    const draft=await (await adminCall('announcements',announcement)).json();assert.equal((await (await call('/api/platform')).json()).announcements.length,0);
    await adminCall('announcements/'+draft.id,{...announcement,status:'published'});assert.equal((await (await call('/api/platform')).json()).announcements[0].title,announcement.title);
    await adminCall('settings',{registration_open:false,chat_readonly:true,reason:'Integration maintenance window'});
    assert.equal((await call('/api/auth/register',{identifier:'paused@example.test',displayName:'Paused',password:'paused-password-2026'})).status,403);
    assert.equal((await call('/api/chat',{text:'Should be blocked'},cookie)).status,403);
    await adminCall('settings',{registration_open:true,chat_readonly:false,reason:'Maintenance window completed'});
    await adminCall('users/local_seedy',{action:'suspend',reason:'Integration suspension check'});
    assert.equal((await call('/api/profile',undefined,cookie)).status,401);
    assert.equal((await call('/api/auth/login',{identifier:'owner@localhost',password:'legacy-owner-password'})).status,401);
    await adminCall('users/local_seedy',{action:'restore',reason:'Integration restoration check'});
    assert.equal((await call('/api/auth/login',{identifier:'owner@localhost',password:'legacy-owner-password'})).status,200);
    const system=await (await fetch(adminBase+'/api/system',{headers:{Cookie:adminCookie}})).json();assert.equal(system.publicSite,'online');assert.equal(system.integrity,'ok');

  }catch(error){console.error(log);throw error;}finally{
    await adminApp?.close();
    if(priorData===undefined)delete process.env.MEMESPACE_DATA_DIR;else process.env.MEMESPACE_DATA_DIR=priorData;
    child.kill('SIGTERM');await new Promise(r=>child.exitCode!==null?r():child.once('exit',r));
    await rm(data,{recursive:true,force:true});
  }
});
