import {stories, coinStories, learning, type Story} from './content';
import {expandedStories, expandedCoinStories, expandedLearning} from './content-expansion';

export type Source = {title: string; url: string};
type ReadingDetail = {takeaway: string; example: string; question: string; sources?: Source[]; sections?: Story['sections']};
export type Reading = Story & ReadingDetail;
const sources = {
  smiley: {title: 'Carnegie Mellon · the original 1982 discussion', url: 'https://www.cs.cmu.edu/~sef/Orig-Smiley.htm'},
  dogecoin: {title: 'Dogecoin · project history', url: 'https://dogecoin.com/dogepedia/articles/history-of-dogecoin/'},
  accounts: {title: 'Ethereum · accounts and keys', url: 'https://ethereum.org/developers/docs/accounts/'},
  explorer: {title: 'Ethereum · reading a block explorer', url: 'https://ethereum.org/developers/docs/data-and-analytics/block-explorers/'},
  approvals: {title: 'Ethereum · token access and revocation', url: 'https://ethereum.org/guides/how-to-revoke-token-access/'},
  security: {title: 'Ethereum · security and scam prevention', url: 'https://ethereum.org/security/'},
  tokens: {title: 'ERC-20 · the token standard', url: 'https://eips.ethereum.org/EIPS/eip-20'},
  fees: {title: 'Ethereum · gas and fees', url: 'https://ethereum.org/developers/docs/gas/'},
  swaps: {title: 'Uniswap · price impact and slippage', url: 'https://developers.uniswap.org/docs/get-started/concepts/traders/swaps'},
  community: {title: 'Discourse · public discussion guidelines', url: 'https://meta.discourse.org/guidelines'},
};

const cultureDetails: Record<string, ReadingDetail> = {
  emoticons: {takeaway: 'A tiny marker can supply the tone a text-only message leaves out.', example: 'Compare “great timing” with “great timing :-)”. Now imagine each follows a delayed game update. The words are identical, but the marker changes how you might read the speaker’s intent. It still cannot replace the surrounding conversation.', question: 'What would a newcomer need to understand the tone?', sources: [sources.smiley], sections: [{title: 'An archived starting point', text: 'On September 19, 1982, Scott Fahlman proposed :-) as a joke marker on a Carnegie Mellon bulletin board. The recovered discussion lets us inspect the proposal in context, including alternatives suggested by other participants. It is a documented moment, not proof that no one ever arranged punctuation into a face before it.'}]},
  macros: {takeaway: 'The image supplies a shared setup; the caption changes the situation.', example: 'Invent a two-panel format: “My plan” above a tidy desk, then “My browser” above forty open tabs. Replace studying with cooking or gaming. Notice which visual relationship must remain for the joke to survive.', question: 'Which part is the template, and which part is your contribution?'},
  lolcats: {takeaway: 'A recognizable voice can function as a template even without one fixed image.', example: 'Write a caption from an animal’s imagined point of view, then try a literal description of the same scene. The first invents a speaker; the second reports what is visible. That difference helps explain why a style of language can spread with many photographs.', question: 'Does the caption describe the image, or give its subject a character?'},
  rickroll: {takeaway: 'Some memes are interactions: expectation and reveal do the work.', example: 'Map the structure without tricking anyone: a promised destination, a different destination, then recognition. If the listener already expects the reveal, the shared ritual may become the joke instead of the surprise.', question: 'Would the reference still work if the audience knew the destination?'},
  doge: {takeaway: 'A character’s visual style and voice can travel into a completely different medium.', example: 'Separate three things when you research Doge: the photograph, the caption style and the cryptocurrency using the name. They are connected, but a fact about one does not automatically describe the others.', question: 'Are you describing a character, a format or a network?', sources: [sources.dogecoin], sections: [{title: 'A photograph behind the format', text: 'Dogecoin’s own history traces its mascot to a 2010 photograph of Kabosu, the Shiba Inu cared for by Atsuko Satō. Keeping the photographer and subject in the record adds context that the copied format often leaves behind.'}]},
  reactions: {takeaway: 'The message around a reaction often matters as much as the clip itself.', example: 'Imagine the same slow clap after “I finished my first project” and after “I deleted my work by accident”. One use may celebrate; the other may feel sarcastic. Ask what the receiver is likely to hear before you post.', question: 'What does the reaction imply in this specific conversation?'},
  remix: {takeaway: 'A useful archive follows transformations, not just a supposed original.', example: 'Build a three-entry remix trail: the earliest version you can actually locate, a variation that changes its meaning, and your own interpretation. Label an uncertain origin as uncertain instead of converting a popular repost into the original.', question: 'Which parts can you document, and which are your interpretation?'},
  community: {takeaway: 'A reference can signal belonging while leaving an outsider without a way in.', example: 'A gaming group uses “one more run” after every loss. To a member it might acknowledge a running joke; to a visitor it is a literal plan. Add one sentence of context when you share an inside joke outside its room.', question: 'Who is included by the reference, and who needs an explanation?', sources: [sources.community]},
  forums: {takeaway: 'Conversation structure helps an explanation outlive the moment it was posted.', example: 'Compare a screenshot of one reply with a thread containing the question, correction and final answer. Only the thread tells you which claim was corrected. When saving a reference, keep a route back to its context.', question: 'Can a future reader reconstruct what question this answered?', sources: [sources.smiley], sections: [{title: 'Read an actual conversation', text: 'The recovered Carnegie Mellon bulletin-board archive includes the discussion around Fahlman’s 1982 proposal. Reading the surrounding posts shows a conversation about tone, not a symbol appearing from nowhere. Modern interfaces can preserve that same relationship between a message and its replies.'}]},
  templates: {takeaway: 'A strong format leaves room for variation while keeping one recognizable relationship.', example: 'Start with “expectation versus reality”. Change the subject three times: a recipe, a software release and a pinball run. Then remove the contrast entirely. You have changed more than the caption; you have changed the format’s logic.', question: 'What is the minimum structure this format needs?'},
  'short-form': {takeaway: 'Timing, audio and editing can carry a template alongside the image.', example: 'Storyboard a six-second remix on paper: two seconds of setup, two of anticipation and two of reveal. Change the reveal while keeping the timing. Then move the cut. Each edit changes what the viewer expects and when the joke lands.', question: 'Does the recognizable cue live in the sound, the image or the timing?'},
  moderation: {takeaway: 'Clear expectations and useful context make a report easier to review.', example: 'A reply looks hostile in isolation, but a preceding message changes its meaning. Report the message through the available control and describe the concern without reposting private information. A moderator needs context, not a pile-on.', question: 'What information would help someone review this fairly?', sources: [sources.community]},
};
const coinDetails: Record<string, ReadingDetail> = {
  dogecoin: {takeaway: 'The cultural origin and the network’s technical identity are separate parts of the story.', example: 'Make two columns in your notes: “cultural reference” and “network facts”. Put the mascot in the first. Put the network name and its documentation in the second. A familiar image cannot substitute for the second column.', question: 'Which claims describe culture, and which require technical evidence?', sources: [sources.dogecoin], sections: [{title: 'A date and people you can trace', text: 'Dogecoin’s project history names Billy Markus and Jackson Palmer and dates the launch to December 6, 2013. It also describes community fundraising for the Jamaican bobsled team and water wells in Kenya in 2014. These examples document participation; they do not predict future results.'}]},
  shiba: {takeaway: 'A shared mascot does not mean shared code, ownership or a shared network.', example: 'Imagine two unrelated tokens displaying the same dog and ticker. A screenshot of the logo cannot distinguish them. Your research note needs the network, the exact identifier and where you independently verified it.', question: 'Would your notes distinguish a look-alike from the asset you meant?', sources: [sources.tokens]},
  networks: {takeaway: 'Always attach a network to an on-chain identifier.', example: 'Write “transaction on network A” instead of just pasting a hash into a note. If an explorer shows no result, check the network before assuming the transaction vanished. A similar-looking identifier is not a cross-chain guarantee.', question: 'Are the website, wallet and explorer referring to the same network?', sources: [sources.explorer]},
  research: {takeaway: 'An explorer records actions; it does not certify someone’s motives.', example: 'A claim says a transfer succeeded. Inspect its network, transaction status, sender, recipient and amount. A successful transfer can support that narrow claim. It cannot prove the recipient’s real-world identity or a promised future service.', question: 'What exact claim does this record support?', sources: [sources.explorer]},
  identity: {takeaway: 'Names help recognition; identifiers make the record inspectable.', example: 'Treat a token research note like a labeled specimen: network, contract or mint identifier, source URL and date checked. Leave an unresolved field blank rather than filling it with a guess based on branding.', question: 'Can another person reproduce your lookup?', sources: [sources.tokens, sources.accounts]},
  permissions: {takeaway: 'A website connection, a signature and a spending allowance are different permissions.', example: 'Suppose an app once received an ERC-20 allowance. Removing that app from the wallet’s connection list does not by itself revoke the on-chain allowance. The connection and the contract’s spending access need separate inspection.', question: 'Which permission does the action in front of you actually change?', sources: [sources.approvals], sections: [{title: 'Disconnecting is not revoking', text: 'For Ethereum token allowances, disconnecting a site does not erase permission already granted to a contract. Revoking that allowance is a separate on-chain action. This distinction is specific to the permission mechanism involved; do not assume every network and wallet uses identical controls.'}]},
  liquidity: {takeaway: 'Visibility and the ability to trade at a quoted price are different things.', example: 'Hypothetical example: a screen values 100 units at 2 each. That arithmetic produces a displayed value of 200, but does not establish that a trade for all 100 units would return 200. Available liquidity, fees and execution conditions affect the result.', question: 'Are you looking at a displayed price or an executable outcome?', sources: [sources.swaps], sections: [{title: 'Price impact and slippage', text: 'In an automated market maker, a swap can move the pool’s price: that is price impact. Changes while a transaction is waiting can also alter its result, commonly discussed as slippage. Uniswap’s documentation describes these separately. Neither is measured by how many people repeat a project’s slogan.'}]},
};

function enrich(items: Story[], details: Record<string, ReadingDetail>): Reading[] {
  return items.map(story => ({...story, ...details[story.id], sections: [...story.sections, ...(details[story.id].sections || [])]}));
}
export const allStories = enrich([...stories, ...expandedStories], cultureDetails).sort((a, b) => {
  const year = (value: string) => Number(value.match(/\d{4}/)?.[0] || (value === 'Now' ? 9998 : 9999));
  return year(a.year) - year(b.year);
});
export const allCoinStories = enrich([...coinStories, ...expandedCoinStories], coinDetails);

type LessonDetail = {track: string; objective: string; exercise: string; explanation: string; sources: Source[]};
const lessonDetails: Record<string, LessonDetail> = {
  ledger: {track: 'Foundations', objective: 'Separate a recorded fact from a claim about the world.', exercise: 'A public record shows that address A sent a token to address B. List one thing the record tells you and one thing it cannot tell you about the people behind the addresses.', explanation: 'The ledger records accepted state changes. It does not guarantee the value of an asset or the truth of a claim someone makes about a transaction.', sources: [sources.explorer]},
  wallets: {track: 'Foundations', objective: 'Identify what can be public and what grants control.', exercise: 'Sort these into public reference or private authority: receiving address, transaction identifier, recovery phrase. Explain why publishing the third is different from sharing the first two.', explanation: 'A recovery phrase can restore access to signing keys. An address or transaction identifier is a public reference, although sharing it can still reveal activity associated with you.', sources: [sources.accounts, sources.security]},
  permissions: {track: 'Safer actions', objective: 'Recognize the scope of a wallet request.', exercise: 'You intended to display your address, but the wallet opens a spending approval. Describe the mismatch in your notes. Connecting an account did not make that second request part of your original intention.', explanation: 'Inspect the request before deciding. A connection does not explain or justify a later signature or spending permission, and an unexpected request should not be approved just to see what happens.', sources: [sources.approvals]},
  tokens: {track: 'Foundations', objective: 'Write a token identity that distinguishes look-alikes.', exercise: 'Two assets use the ticker SPACE. Write the additional fields you would need to distinguish them: network and contract or mint identifier. Do not use an invented live address for this exercise.', explanation: 'Names and symbols can be reused. The ERC-20 standard exposes name and symbol as optional descriptive fields; it does not make them globally unique identifiers.', sources: [sources.tokens]},
  fees: {track: 'Safer actions', objective: 'Distinguish submission, execution and confirmation.', exercise: 'An app says “submitted” while an explorer reports a failed transaction. Which status should the app show next? Record why a submitted request is not the same as the intended action succeeding.', explanation: 'The network still needs to process the request. On Ethereum, a failed transaction may consume gas for work already performed, so failure does not necessarily mean zero fee.', sources: [sources.fees]},
  culture: {track: 'Culture', objective: 'Separate community meaning from technical evidence.', exercise: 'Write one sentence explaining a mascot’s cultural appeal, then another describing a fact that would need on-chain verification. Keep popularity out of the second sentence as evidence of safety.', explanation: 'Recognition can explain why a story spreads. It cannot establish a contract’s behavior, a person’s honesty or an asset’s future performance.', sources: [sources.dogecoin]},
  research: {track: 'Safer actions', objective: 'Build a reproducible record of a claim.', exercise: 'Use a transaction example from an explorer’s documentation. Note the network, identifier and status, then state exactly what those fields support. You do not need to connect a wallet or submit a transaction.', explanation: 'Start with the network and identifier so you know which record you are examining. A slogan or screenshot may omit the context needed to reproduce the claim.', sources: [sources.explorer]},
  security: {track: 'Safer actions', objective: 'Recognize a request that must never be fulfilled.', exercise: 'An unsolicited account with a familiar avatar asks for your recovery phrase to “verify” a wallet. Write a response that reveals no secrets, then identify an independent route to check the impersonation.', explanation: 'No legitimate support interaction needs your recovery phrase. Giving only part of it or using a private message does not make the request legitimate.', sources: [sources.security]},
  communities: {track: 'Culture', objective: 'Keep useful explanations findable and understandable.', exercise: 'Turn “it does not work” into a useful gaming-channel question: name the cabinet, input method, expected outcome and what happened. Reply in the same conversation when you discover the answer.', explanation: 'A topic gives the discussion a home, replies preserve context, and searchable history lets someone find the explanation later. Removing context makes the same questions harder to answer.', sources: [sources.community]},
};
const lessonOrder = ['ledger', 'wallets', 'tokens', 'permissions', 'fees', 'research', 'security', 'culture', 'communities'];
export const allLearning = [...learning, ...expandedLearning].map(lesson => ({...lesson, ...lessonDetails[lesson.id]})).sort((a, b) => lessonOrder.indexOf(a.id) - lessonOrder.indexOf(b.id));
export type Lesson = typeof allLearning[number];

export function readingText(story: Reading) {
  return [story.title, story.summary, story.tags.join(' '), story.takeaway, story.example, story.question, ...story.sections.map(section => section.title + ' ' + section.text)].join(' ');
}
export function lessonText(lesson: Lesson) {
  return [lesson.title, lesson.intro, lesson.objective, ...lesson.paragraphs, lesson.exercise, lesson.question, ...lesson.answers, lesson.explanation].join(' ');
}
export function readingMinutes(story: Reading) {
  return Math.max(1, Math.ceil(readingText(story).split(/\s+/).length / 200));
}
