import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{userId:text('user_id').primaryKey(),name:text('name').notNull(),bio:text('bio').notNull().default(''),updatedAt:integer('updated_at').notNull()});
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),userId:text('user_id').notNull(),text:text('text').notNull(),channel:text('channel').notNull().default('general'),replyTo:text('reply_to'),editedAt:integer('edited_at').notNull().default(0),hiddenAt:integer('hidden_at').notNull().default(0),hiddenReason:text('hidden_reason').notNull().default(''),createdAt:integer('created_at').notNull()},t=>[index('idx_messages_created').on(t.createdAt),index('idx_messages_channel_created').on(t.channel,t.createdAt),index('idx_messages_user_created').on(t.userId,t.createdAt)]);
export const reports=sqliteTable('reports',{id:text('id').primaryKey(),userId:text('user_id').notNull(),messageId:text('message_id').notNull(),createdAt:integer('created_at').notNull(),status:text('status').notNull().default('open'),reviewedAt:integer('reviewed_at').notNull().default(0),reviewedBy:text('reviewed_by').notNull().default(''),resolutionNote:text('resolution_note').notNull().default('')},t=>[uniqueIndex('idx_reports_user_message').on(t.userId,t.messageId),index('idx_reports_status_created').on(t.status,t.createdAt)]);
export const savedItems=sqliteTable('saved_items',{id:text('id').primaryKey(),userId:text('user_id').notNull(),kind:text('kind').notNull(),itemKey:text('item_key').notNull(),payload:text('payload').notNull(),updatedAt:integer('updated_at').notNull()},t=>[uniqueIndex('idx_saved_user_kind_key').on(t.userId,t.kind,t.itemKey)]);
export const likes=sqliteTable('likes',{id:text('id').primaryKey(),userId:text('user_id').notNull(),messageId:text('message_id').notNull()},t=>[uniqueIndex('idx_likes_user_message').on(t.userId,t.messageId),index('idx_likes_message').on(t.messageId)]);
export const accounts=sqliteTable('accounts',{userId:text('user_id').primaryKey(),email:text('email').notNull(),passwordHash:text('password_hash').notNull(),passwordSalt:text('password_salt').notNull(),displayName:text('display_name').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),lastLoginAt:integer('last_login_at').notNull().default(0),failedAttempts:integer('failed_attempts').notNull().default(0),lockedUntil:integer('locked_until').notNull().default(0),deletedAt:integer('deleted_at').notNull().default(0),suspendedAt:integer('suspended_at').notNull().default(0),suspensionReason:text('suspension_reason').notNull().default(''),legacyClaimedAt:integer('legacy_claimed_at').notNull().default(0)},t=>[uniqueIndex('idx_accounts_email').on(t.email),index('idx_accounts_created').on(t.createdAt)]);
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),tokenHash:text('token_hash').notNull(),userId:text('user_id').notNull(),label:text('label').notNull(),createdAt:integer('created_at').notNull(),lastSeenAt:integer('last_seen_at').notNull(),expiresAt:integer('expires_at').notNull(),revokedAt:integer('revoked_at').notNull().default(0)},t=>[uniqueIndex('idx_sessions_token_hash').on(t.tokenHash),index('idx_sessions_user').on(t.userId),index('idx_sessions_expiry').on(t.expiresAt)]);

export const platformSettings=sqliteTable('platform_settings',{key:text('key').primaryKey(),value:text('value').notNull(),updatedAt:integer('updated_at').notNull()});
export const announcements=sqliteTable('announcements',{id:text('id').primaryKey(),title:text('title').notNull(),body:text('body').notNull(),tone:text('tone').notNull().default('info'),status:text('status').notNull().default('draft'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),publishedAt:integer('published_at').notNull().default(0)},t=>[index('idx_announcements_status').on(t.status,t.publishedAt)]);
