'use client';
import {Maximize,Minimize,Pause,Play,RotateCcw,Volume2,VolumeX,HelpCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle,DialogTrigger} from '@/components/ui/dialog';
import type {ReactNode} from 'react';
export function GameTools({paused,pause,restart,sound,fullscreen,rules}:{paused?:boolean;pause?:()=>void;restart:()=>void;sound:{enabled:boolean;toggle:()=>void};fullscreen:{full:boolean;toggle:()=>void;container?:HTMLElement|null};rules:ReactNode}){
 return <div className="arcade-tools">{pause&&<button onClick={pause} aria-label={paused?'Resume game':'Pause game'}>{paused?<Play/>:<Pause/>}<span>{paused?'Resume':'Pause'}</span></button>}<button onClick={restart} aria-label="Restart this game"><RotateCcw/><span>Restart</span></button><button onClick={sound.toggle} aria-label={sound.enabled?'Mute game sound':'Enable game sound'} aria-pressed={sound.enabled}>{sound.enabled?<Volume2/>:<VolumeX/>}</button><Dialog onOpenChange={open=>{if(open&&!paused)pause?.()}}><DialogTrigger asChild><button aria-label="How to play"> <HelpCircle/></button></DialogTrigger><DialogContent className="arcade-rules" container={fullscreen.full?fullscreen.container:undefined}><DialogTitle>How to play</DialogTitle><DialogDescription>Controls, objectives and the rules for this cabinet.</DialogDescription><div>{rules}</div></DialogContent></Dialog><button onClick={fullscreen.toggle} aria-label={fullscreen.full?'Exit fullscreen':'Enter fullscreen'}>{fullscreen.full?<Minimize/>:<Maximize/>}</button></div>
}
export function Stat({label,value,accent=false}:{label:string;value:ReactNode;accent?:boolean}){return <div className={'arcade-stat '+(accent?'accent':'')}><span>{label}</span><strong>{value}</strong></div>}
export function PauseCover({paused,over,title,description,resume,restart}:{paused:boolean;over:boolean;title:string;description:string;resume:()=>void;restart:()=>void}){if(!paused&&!over)return null;return <div className="arcade-pause"><div><p className="arcade-eyebrow">{over?'SESSION COMPLETE':'TAKE YOUR TIME'}</p><h3>{over?title:'Game paused'}</h3><p>{over?description:'Your game waits for you. Resume when you’re ready.'}</p><button className="arcade-primary" onClick={over?restart:resume}>{over?'Play again':'Resume game'}<Play/></button></div></div>}
