name: DPN Enterprise Security

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: "11 11 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: enterprise-security-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  enterprise-security:
    permissions:
      contents: read
      pull-requests: read
      security-events: write
      id-token: write
    uses: DPN-Technology/.github/.github/workflows/dpn-enterprise-security.yml@4da9e51899f69da9f08532aa02f94095fa628261
    with:
      run_dependency_review: true
      dependency_fail_severity: high
      run_scorecard: true
      upload_scorecard_sarif: false
